###############################################################################
# SET PREPROCESSING PARAMETERS                                                #
###############################################################################
RAW_DATA_PATH: data/raw
PROCESSED_DATA_DIR: data/processed
DATA_SLICE: 1500
NUM_WORKERS: 4
DOWNSAMPLE_THRESHOLD: 200

###############################################################################
# SET TRAINING PARAMETERS                                                     #
###############################################################################
SUMMARY_PATH: logs

MODEL: LSTM
EPOCHS: 50
BATCH_SIZE: 64
HIDDEN_SIZE: 256
NUM_LAYERS: 3
DROPOUT: 0.5
LR: 0.001

###############################################################################
# SET INFERENCE PARAMETERS                                                    #
###############################################################################
INFERENCE_MODEL: models/LSTM/50.pt
INFERENCE_DATA: data/processed/test_data.pkl
INFERENCE_LABEL: data/processed/test_label.pkl