###############################################################################
# SET PREPROCESSING PARAMETERS                                                #
###############################################################################
RAW_DATA_PATH: data/raw
PROCESSED_DATA_DIR: data/processed
DATA_SLICE: 2500
NUM_WORKERS: 4
DOWNSAMPLE_THRESHOLD: 350

###############################################################################
# SET TRAINING PARAMETERS                                                     #
###############################################################################
SUMMARY_PATH: logs

MODEL: LSTM
EPOCHS: 100
BATCH_SIZE: 64
HIDDEN_SIZE: 128
NUM_LAYERS: 2
DROPOUT: 0.3
LR: 0.001

###############################################################################
# SET INFERENCE PARAMETERS                                                    #
###############################################################################
INFERENCE_MODEL: models/LSTM/50.pt
INFERENCE_DATA: data/processed/test_data.pkl
INFERENCE_LABEL: data/processed/test_label.pkl