###############################################################################
# SET PREPROCESSING PARAMETERS                                                #
###############################################################################
RAW_DATA_PATH: data/raw
PROCESSED_DATA_DIR: data/processed
DATA_SLICE: 1500
NUM_WORKERS: 4
DOWNSAMPLE_THRESHOLD: 200

###############################################################################
# SET TRAINING PARAMETERS                                                     #
###############################################################################
SUMMARY_PATH: logs

MODEL: CNN
EPOCHS: 50
BATCH_SIZE: 256
HIDDEN_SIZE: 64
NUM_LAYERS: 1
DROPOUT: 0.3
LR: 0.001